import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Layout/Navbar";
import Footer from "@/Layout/Footer";
import NavHelmat from "@/Layout/NavHelmet";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const kaushan = localFont({
  src: "./fonts/KaushanScript-Regular.ttf",
  variable: "--font-kaushan",
  weight: "400",
});

export const aclonica = localFont({
  src: "./fonts/Aclonica-Regular.ttf",
  variable: "--font-Aclonica",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Sunny",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <NavHelmat />
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
